# Generated by Django 4.2.30 on 2026-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noutbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('narx', models.IntegerField()),
            ],
        ),
    ]
