# Generated by Django 4.2.30 on 2026-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dars', '0002_noutbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.CharField(max_length=250)),
                ('brend', models.CharField(max_length=250)),
            ],
        ),
    ]
